spring.application.name=management

server.port=${PORT:8080}

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/ProjectManagement}

ai.service.url=${AI_SERVICE_URL:http://127.0.0.1:5000}